apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:oA6jrFaMQbJZlhl58sWJ7XAnxzyuDgo=,iv:4pE4uohjwNTkp8ekiAvgDKHMVK693nQHHFgouzolQ5o=,tag:B2Oo15VMewOjOaWUmIPPUA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:JLSLeyjW1GaexDgXqK9QsllxZ2ffWY1hFzwsw9G8VwpI2IGhig==,iv:po1ITNTCPkQfiOAKKlTtw8x7Pins4d0EiqgZbihpuH8=,tag:XQBo+EHhYTd7r6oo9nEEwA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:RjshqGXpAbGVdf8YtRD2,iv:zpkn8xb5z6/oAZPeJHzZp0aWf2H+EbaIKfGAQvDwKpE=,tag:w3lvP9hwluEKxE3u1CeatA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hqvck62ky4r7jwvrw3f8lncdtp2cvlypkhr9t488hl0uaw5zey5qse0w4q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdEQ0cmZ3R2tEVlh6QjZo
            YWEzQmRJbTAzSGVZRW1zNmd5bGlYZGVaa2xzClpwSkI1SmpuTkY2d2Q4cU5GcXVQ
            YjlRWWJGckc4V1diSksydHRWVmZyUGsKLS0tIDFCdldaYXQ4cGdxSCtGR3EyYW12
            RjU3QTNqVXNDL2syN2xNdnNXblhIRUEKn6ZNUEVUAkHIokCkU29/1idCNJPXiPLz
            Tuur9zwnuhLvtVnIizLvWt6uWg6nDkCkDkM4gPlnXK0+xDydBVhIJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-29T09:59:45Z"
    mac: ENC[AES256_GCM,data:2DtLKRu2C8uNLfKrrpcfdhWjobZHu91tn0hCdbcKHXyLMTgTVpnNpG5cNqwgAwYBihRXTcJbB+zAS4+/KXI8bA/NqofrvOZyT1m+maRFpdeXP0BBpoJ4fo+fWdNcN47/9tQhPxmaPtQT18LLtQTe1bvbbza0QuyIUxfH8vdIkcY=,iv:EzwYKw2R+OT5ZSfowlymHMzYaq2l5IZ0jKgnuqVna1s=,tag:zvPD3LOpXRWlXoYDiZcMQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
