apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:pfQGbpOiRePPbEndYprDoeyWNV7hhBkrOj+TFSuKUfslWuigY+V6mQ==,iv:no0pBYL8PbwYHqW5NbjQ8dw+4BRfeYzUa21cYoMR9ZE=,tag:np3UrG9nY4zfcJfX3gMVow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hqvck62ky4r7jwvrw3f8lncdtp2cvlypkhr9t488hl0uaw5zey5qse0w4q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbWNCTnduenh2czdSN2ky
            R2tsbzZFOGpjb3dkaDUzdjJzZzE1SDNGdkVzCmdiMWdpalVLRzJJZ1dxQkNtQTJH
            ZCtaY2pGaTg4dklET3BKeU56RWdGREEKLS0tIHhhLzFrQ1ljbHBRQnZiTG02L0NW
            Zzg1WUxBSFZJRFRCT0d6MEZOSWtBZFkKmavSC0r2TNauiLd1VE8wXHkmIRi55+kO
            MCuKJjYTx44/H7U0J/Nx4O1zX8loOm5sHJo3etBvFbeqeQ7nWzcYsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-29T09:59:45Z"
    mac: ENC[AES256_GCM,data:h71PJ+Z3o6UhhgD6Z6QLYpi7OLjYRUzQ3LxJrpHLBMVSD1F0gmi88RLWz69J/Y1xJ8T9bcRPOnyMF8/k2wsv74sdbCxgL6/EE1hExB67dR5QcF3cX4mgWCrP+JYtjufmBHge6XAYbAr3aIl2QmS22JaVT/m9VrcxHDX2gA98d1o=,iv:DazzaOk/fCtz1Z8A1KwMevZppI50pASRkMmj2swiIZI=,tag:kw7I4ipvojSPSddgoLfVHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
