---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Aest/UTC"
  KUBE_VIP_ADDR: "192.168.1.21"
  METALLB_LB_RANGE: "192.168.1.25-192.168.1.49"
  METALLB_K8S_GATEWAY_ADDR: "192.168.1.25"
  METALLB_INGRESS_ADDR: "192.168.1.26"
